#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true

[[custom_plugin]]
  name = 'lilydjwg/colorizer'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
   name = "lang#markdown"
  
[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#python"
  format_on_save = 1

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#puppet"

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "checkers"
  enable = false
